GET http://localhost:3000/pelicula/index
Authorization: Bearer 
###

POST http://localhost:3000/pelicula/alta
Authorization: Bearer 
Content-Type: application/json

{
    "nombre": "Terminator",
    "director": "James Cameron",
    "lanzamiento": 1984,
    "genero": "Accion",
    "descripcion": "Una máquina del futuro es enviada al pasado"
}
###
DELETE http://localhost:3000/pelicula/baja/id
Authorization: Bearer 

###
PUT http://localhost:3000/pelicula/editar/6807d1dd1ac738776a72a1b7
Authorization: Bearer 
Content-Type: application/json

{
    "nombre": "Rambo",
    "director": "James Cameron",
    "lanzamiento": 1984,
    "genero": "Accion",
    "descripcion": "Una máquina del futuro es enviada al pasado"
}

###

GET http://localhost:3000/pelicula/actualizar/id
Authorization: Bearer 

