GET http://localhost:3000/user/index 

###
POST http://localhost:3000/user/alta
Content-Type: application/json

{
    "userName": "bruno88",
    "email": "bruno88@gmail.com",
    "password": "123"
}

###
PUT http://localhost:3000/user/editar/id
Authorization: Bearer 
Content-Type: application/json

{
    "userName": "jor",
    "email": "bruno88@gmail.com",
    "password": "123"
}

###
DELETE http://localhost:3000/user/eliminar/id
Authorization: Bearer 

###
GET http://localhost:3000/user/perfil/id
Authorization: Bearer 

###
GET http://localhost:3000/user/mispost/id
Authorization: Bearer 